import * as vscode from 'vscode';
import { spawn } from 'child_process';

function runCLI(args: string[], cwd?: string) {
processCodeBlock(cwd, shell);
}

export function activate(context: vscode.ExtensionContext) {
  const cmds = [
    ['refacto.stabilize', () => const cli = spawn('node', ['dist/index.js', ...['stabilize', '--routes', '10']], { cwd: cwd ?? `${__dirname}/../../cli`, shell: false });
  let output = '';
  cli.stdout.on('data', (d) => output += d.toString());
  cli.stderr.on('data', (d) => output += d.toString());
  cli.on('close', (code) => {
    const ch = vscode.window.createOutputChannel('Refactogent');
    ch.appendLine(output);
    ch.show(true);
    if (code !== 0) vscode.window.showErrorMessage(`Refactogent CLI exited with code ${code}`);
  });],
    ['refacto.organizeOnly', () => const cli = spawn('node', ['dist/index.js', ...['plan', '--mode', 'organize-only']], { cwd: cwd ?? `${__dirname}/../../cli`, shell: false });
  let output = '';
  cli.stdout.on('data', (d) => output += d.toString());
  cli.stderr.on('data', (d) => output += d.toString());
  cli.on('close', (code) => {
    const ch = vscode.window.createOutputChannel('Refactogent');
    ch.appendLine(output);
    ch.show(true);
    if (code !== 0) vscode.window.showErrorMessage(`Refactogent CLI exited with code ${code}`);
  });],
    ['refacto.nameHygiene', () => const cli = spawn('node', ['dist/index.js', ...['plan', '--mode', 'name-hygiene']], { cwd: cwd ?? `${__dirname}/../../cli`, shell: false });
  let output = '';
  cli.stdout.on('data', (d) => output += d.toString());
  cli.stderr.on('data', (d) => output += d.toString());
  cli.on('close', (code) => {
    const ch = vscode.window.createOutputChannel('Refactogent');
    ch.appendLine(output);
    ch.show(true);
    if (code !== 0) vscode.window.showErrorMessage(`Refactogent CLI exited with code ${code}`);
  });],
    ['refacto.microSimplify', () => const cli = spawn('node', ['dist/index.js', ...['plan', '--mode', 'micro-simplify']], { cwd: cwd ?? `${__dirname}/../../cli`, shell: false });
  let output = '';
  cli.stdout.on('data', (d) => output += d.toString());
  cli.stderr.on('data', (d) => output += d.toString());
  cli.on('close', (code) => {
    const ch = vscode.window.createOutputChannel('Refactogent');
    ch.appendLine(output);
    ch.show(true);
    if (code !== 0) vscode.window.showErrorMessage(`Refactogent CLI exited with code ${code}`);
  });],
    ['refacto.publicSurface', () => vscode.window.showInformationMessage('Public surface map will be generated by the CLI (stub).')]
  ] as const;

  cmds.forEach(([name, fn]) => {
    const disposable = vscode.commands.registerCommand(name, fn);
    context.subscriptions.push(disposable);
  });
}

export function deactivate() {}

function extractedFunction(spawn: any, args: any, cwd: any, __dirname: any, shell: any, stdout: any, on: any, d: any, toString: any, stderr: any, code: any, vscode: any, window: any, createOutputChannel: any, appendLine: any, show: any, showErrorMessage: any): void {
  const cli = spawn('node', ['dist/index.js', ...args], { cwd: cwd ?? `${__dirname}/../../cli`, shell: false });
  let output = '';
  cli.stdout.on('data', (d) => output += d.toString());
  cli.stderr.on('data', (d) => output += d.toString());
  cli.on('close', (code) => {
      const ch = vscode.window.createOutputChannel('Refactogent');
      ch.appendLine(output);
      ch.show(true);
      if (code !== 0) vscode.window.showErrorMessage(`Refactogent CLI exited with code ${code}`);
    });
}

function extractedFunction(spawn: any, args: any, cwd: any, __dirname: any, shell: any, stdout: any, on: any, d: any, toString: any, stderr: any, code: any, vscode: any, window: any, createOutputChannel: any, appendLine: any, show: any, showErrorMessage: any): void {
  const cli = spawn('node', ['dist/index.js', ...args], { cwd: cwd ?? `${__dirname}/../../cli`, shell: false });
  let output = '';
  cli.stdout.on('data', (d) => output += d.toString());
  cli.stderr.on('data', (d) => output += d.toString());
  cli.on('close', (code) => {
      const ch = vscode.window.createOutputChannel('Refactogent');
      ch.appendLine(output);
      ch.show(true);
      if (code !== 0) vscode.window.showErrorMessage(`Refactogent CLI exited with code ${code}`);
    });
}

function processCodeBlock(cwd: cwd, shell: false): void {
    const cli = spawn('node', ['dist/index.js', ...args], { cwd: cwd ?? `${__dirname}/../../cli`, shell: false });
  let output = '';
  cli.stdout.on('data', (d) => output += d.toString());
  cli.stderr.on('data', (d) => output += d.toString());
  cli.on('close', (code) => {
      const ch = vscode.window.createOutputChannel('Refactogent');
      ch.appendLine(output);
      ch.show(true);
      if (code !== 0) vscode.window.showErrorMessage(`Refactogent CLI exited with code ${code}`);
    });
}