name: Deploy Landing Page

on:
  push:
    branches:
      - main
    paths:
      - 'packages/landing/**'
      - '.github/workflows/deploy-landing.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Deploy to S3
        run: |
          aws s3 sync packages/landing/ s3://${{ secrets.S3_BUCKET_NAME }}/ \
            --exclude "*.sh" \
            --exclude "*.json" \
            --exclude "*.md" \
            --exclude "package.json" \
            --exclude "package-lock.json" \
            --exclude "node_modules/*" \
            --cache-control "public, max-age=31536000, immutable" \
            --exclude "index.html"

          # Upload index.html with shorter cache for updates
          aws s3 cp packages/landing/index.html s3://${{ secrets.S3_BUCKET_NAME }}/index.html \
            --cache-control "public, max-age=3600, must-revalidate" \
            --content-type "text/html"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Deployment complete
        run: |
          echo "✅ Landing page deployed successfully!"
          echo "🌐 CloudFront URL: https://${{ secrets.CLOUDFRONT_DOMAIN }}"
